### PR TITLE
fixing installation project file

### PR DESCRIPTION
**Pull request by onelsonic**

### CODE REVIEW

**Comment by tong** [comment]
What does this actually 'fix'?
The extra fields aren't used right now but could be to create a more detailed report after all projects are built.

**Comment by onelsonic** [comment]
On windows the examples compilation will not launch until I replaced this line in the project file:
See commit :
https://github.com/armory3d/armory_examples_browser/pull/6/commits/20fa3a587394935b93aa45a9702c0f58cd5d748d

Otherwise the function was throwing a too few argument error

**Comment by tong** [comment]
I cannot reproduce this.
Can you post the error?

**Comment by onelsonic** [comment]
```
haxe build-examples.hxml
src/Project.hx:37: characters 27-33 : { time : Int, src : String, project : String, group : String, code : Int, background : Bool } should be { time : Int, project : String, code : Int }
src/Project.hx:37: characters 27-33 : { time : Int, src : String, project : String, group : String, code : Int, background : Bool } has extra field background
src/Project.hx:37: characters 27-33 : For function argument 'x'
```

**Comment by tong** [comment]
I've added the missing fields to the type definition, should work now.

**Pull request closed without merging**
